name: E2E in custom container
on: [ push ]
jobs:
  firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install --force

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: firefox
          spec: cypress/integration/jsonSchemaInjector.js